FROM maven:3-eclipse-temurin-21 as build
RUN mkdir /app/
COPY ./ /app/
WORKDIR /app/
RUN mvn clean package -Ps_pre -DskipTests

FROM eclipse-temurin:21
LABEL authors="Grzegorz Jewusiak"
COPY --from=build /app/target/*.jar app.jar
#RUN mkdir "db"

ENTRYPOINT ["java","-jar","/app.jar"]

HEALTHCHECK --start-interval=3s --interval=60s --start-period=20s --timeout=5s --retries=10 \
  CMD curl -s http://localhost:8080 >/dev/null || exit 1
