FROM maven:3-eclipse-temurin-17 as build
RUN mkdir /app/
COPY ./ /app/
WORKDIR /app/
RUN mvn clean package -Ps_pre -DskipTests

FROM eclipse-temurin:17
LABEL authors="Grzegorz Jewusiak"
COPY --from=build /app/target/*.jar app.jar
COPY ./secrets/gcp_server_key.json secrets/gcp_server_key.json
#RUN mkdir "db"

ENTRYPOINT ["java","-jar","/app.jar"]
